name: Deploy Firebase Hosting (manual)

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Deploy channel (live or preview channel name)'
        required: false
        default: 'live'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: '${{ github.event.inputs.channel }}'
          projectId: 'project-bridge-cm'
